exports['snippet-bot responds to PR sets a "failure" context on PR 1'] = {
  name: 'Mismatched region tag',
  conclusion: 'failure',
  head_sha: 'ce03c1b7977aadefb5f6afc09901f106ee6ece6a',
  output: {
    title: 'Mismatched region tag detected.',
    summary: 'Some new files have mismatched region tag',
    text:
      "test.py:5, tag `hello` has already started\ntest.py:10, tag `lol` doesn't have a matching start tag\ntest.py:8, tag `world` doesn't have a matching end tag",
  },
};

exports['snippet-bot responds to issue reports the scan result 1'] = {
  body:
    "<!-- probot comment [11359653]-->\n\n## snippet-bot scan result\nLife is too short to manually check unmatched region tags.\nHere is the result:\n- [ ] [test.py:3](https://github.com/tmatsuo/python-docs-samples/blob/abcde/test.py#L3), tag `lol` doesn't have a matching start tag\n- [ ] [test.py:1](https://github.com/tmatsuo/python-docs-samples/blob/abcde/test.py#L1), tag `hello` doesn't have a matching end tag\n\n---\nReport generated by [snippet-bot](https://github.com/apps/snippet-bot).\nIf you find problems with this result, please file an issue at:\nhttps://github.com/googleapis/repo-automation-bots/issues.\n",
};

exports[
  'snippet-bot responds to issue reports failure upon download failure 1'
] = {
  body:
    '<!-- probot comment [11359653]-->\n\n## snippet-bot scan result\nFailed running the full scan: Error: Failed to scan files: unexpected response Forbidden.\n\n---\nReport generated by [snippet-bot](https://github.com/apps/snippet-bot).\nIf you find problems with this result, please file an issue at:\nhttps://github.com/googleapis/repo-automation-bots/issues.\n',
};
