exports['check for config whether config is a valid YAML object should return error message if YAML is invalid 1'] = `
File is not properly configured YAML
`

exports['check for config whether YAML file has valid schema should fail if YAML has any other properties than the ones specified 1'] = [
  {
    "wrongProperty": {
      "additionalProperty": "notTheRules"
    },
    "message": "should NOT have additional properties"
  }
]

exports['check for config whether YAML file has valid schema should fail if title does not match first author 1'] = [
  {
    "wrongProperty": {
      "allowedValue": "^chore: regenerate README$"
    },
    "message": "should be equal to constant"
  }
]

exports['check for config whether YAML file has valid schema should fail if title does not match third author 1'] = [
  {
    "wrongProperty": {
      "allowedValue": "^chore: autogenerated discovery document update"
    },
    "message": "should be equal to constant"
  }
]

exports['check for config whether YAML file has valid schema should fail if author is not allowed 1'] = [
  {
    "wrongProperty": {
      "allowedValues": [
        "googleapis-publisher",
        "yoshi-automation",
        "yoshi-code-bot"
      ]
    },
    "message": "should be equal to one of the allowed values"
  }
]

exports['check for config whether YAML file has valid schema should fail if it does not have title property 1'] = [
  {
    "wrongProperty": {
      "missingProperty": "title"
    },
    "message": "should have required property 'title'"
  }
]

exports['check for config whether YAML file has valid schema should fail if config is empty 1'] = [
  {
    "wrongProperty": {
      "type": "object"
    },
    "message": "should be object"
  }
]

exports['check for config whether YAML file has valid schema should fail if there are duplicate items 1'] = [
  {
    "wrongProperty": {
      "i": 1,
      "j": 0
    },
    "message": "should NOT have duplicate items (items ## 0 and 1 are identical)"
  }
]
