requestsize:
  enabled: true

# Turn of product-based auto-labelling
product: false

# Label bots by code path
path:
  pullrequest: true
  labelprefix: 'bot: '
  paths:
    packages:
      auto-approve: 'auto approve'
      auto-label: 'auto label'
      bazel-bot: 'bazel bot'
      blunderbuss: 'blunderbuss'
      canary-bot: 'canary'
      cherry-pick-bot: 'cherry-pick'
      conventional-commit-lint: 'conventional-commit-lint'
      do-not-merge: 'do not merge'
      failurechecker: 'failurechecker'
      flakybot: 'flakybot'
      generated-files-bot: 'generated-files-bot'
      header-checker-lint: 'license header'
      label-sync: 'label-sync'
      merge-on-green: 'merge on green'
      owl-bot: 'owl-bot'
      owlbot-bootstrapper: 'owl-bot bootstrapper'
      policy: 'policy'
      release-please: 'release please'
      release-trigger: 'release-trigger'
      repo-metadata-lint: 'repo-metadata-lint'
      secret-rotator: 'secret-rotator'
      slo-stat-bot: 'slo-stat-bot'
      snippet-bot: 'snippet-bot'
      sync-repo-settings: 'sync-repo-settings'
      trusted-contribution: 'trusted contributor'
