# See https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss

assign_issues_by:
  - labels:
    - 'bot: release-please'
    to:
    - chingor13
  - labels:
    - 'bot: snippet-bot'
    to:
    - tmatsuo

assign_prs_by:
  - labels:
    - 'bot: release-please'
    to:
    - bcoe
    - chingor13
  - labels:
    - 'bot: snippet-bot'
    to:
    - tmatsuo
  - labels:
    - 'bot: owl-bot'
    to:
    - chingor13
    - SurferJeffAtGoogle

assign_issues:
  - chingor13
  - SurferJeffAtGoogle
assign_prs:
  - bcoe
  - chingor13
  - sofisl
  - SurferJeffAtGoogle
