# See https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss

assign_issues_by:
  - labels:
    - 'bot: auto-label'
    to:
    - sofisl
  - labels:
    - 'bot: generated-files-bot'
    - 'bot: header-checker-lint'
    - 'bot: monitoring-system'
    to:
    - chingor13
  - labels:
    - 'bot: merge-on-green'
    to:
    - sofisl
  - labels:
    - 'bot: release-please'
    to:
    - bcoe
    - chingor13
  - labels:
    - 'bot: snippet-bot'
    to:
    - tmatsuo
  - labels:
    - 'bot: owl-bot'
    to:
    - SurferJeffAtGoogle

assign_prs_by:
  - labels:
    - 'bot: auto-label'
    to:
    - sofisl
  - labels:
    - 'bot: generated-files-bot'
    - 'bot: header-checker-lint'
    - 'bot: monitoring-system'
    to:
    - chingor13
  - labels:
    - 'bot: merge-on-green'
    to:
    - sofisl
  - labels:
    - 'bot: release-please'
    to:
    - bcoe
    - chingor13
  - labels:
    - 'bot: snippet-bot'
    to:
    - tmatsuo
  - labels:
    - 'bot: owl-bot'
    to:
    - SurferJeffAtGoogle

assign_prs:
  - googleapis/github-automation
