# See https://github.com/googleapis/repo-automation-bots/tree/master/packages/blunderbuss

testing: "config schema check"
assign_issues_by:
  - labels:
    - 'bot: auto-label'
    to:
    - nicoleczhu
    - sofisl
  - labels:
    - 'bot: blunderbuss'
    to:
    - kvg
  - labels:
    - 'bot: flakybot'
    - 'bot: do-not-merge'
    to:
    - tbp
  - labels:
    - 'bot: conventional-commit-lint'
    - 'bot: failurechecker'
    to:
    - bcoe
  - labels:
    - 'bot: generated-files-bot'
    - 'bot: header-checker-lint'
    - 'bot: monitoring-system'
    to:
    - chingor13
  - labels:
    - 'bot: label-sync'
    - 'bot: sync-repo-settings'
    to:
    - JustinBeckwith
  - labels:
    - 'bot: merge-on-green'
    to:
    - sofisl
  - labels:
    - 'bot: release-please'
    to:
    - bcoe
    - chingor13
  - labels:
    - 'bot: slo-stat-bot'
    to:
    - orthros
  - labels:
    - 'bot: snippet-bot'
    to:
    - tmatsuo
  - labels:
    - 'bot: trusted-contribution'
    to:
    - crwilcox

assign_prs_by:
  - labels:
    - 'bot: auto-label'
    to:
    - nicoleczhu
    - sofisl
  - labels:
    - 'bot: blunderbuss'
    to:
    - kvg
  - labels:
    - 'bot: flakybot'
    - 'bot: do-not-merge'
    to:
    - tbp
  - labels:
    - 'bot: conventional-commit-lint'
    - 'bot: failurechecker'
    to:
    - bcoe
  - labels:
    - 'bot: generated-files-bot'
    - 'bot: header-checker-lint'
    - 'bot: monitoring-system'
    to:
    - chingor13
  - labels:
    - 'bot: label-sync'
    - 'bot: sync-repo-settings'
    to:
    - JustinBeckwith
  - labels:
    - 'bot: merge-on-green'
    to:
    - sofisl
  - labels:
    - 'bot: release-please'
    to:
    - bcoe
    - chingor13
  - labels:
    - 'bot: slo-stat-bot'
    to:
    - orthros
  - labels:
    - 'bot: snippet-bot'
    to:
    - tmatsuo
  - labels:
    - 'bot: trusted-contribution'
    to:
    - crwilcox
