# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: gcr.io/cloud-builders/docker
    id: "build-docker"
    waitFor: ["-"]
    dir: packages/release-trigger
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/release-trigger"
      - "."

  - name: gcr.io/cloud-builders/docker
    id: "push-docker"
    waitFor: ["build-docker"]
    args: ["push", "gcr.io/$PROJECT_ID/release-trigger"]

  - name: gcr.io/cloud-builders/gcloud
    id: "deploy-cloud-run-backend"
    waitFor: ["push-docker"]
    entrypoint: gcloud
    dir: $_DIRECTORY
    args:
      - "run"
      - "deploy"
      - "release-trigger-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/release-trigger"
      - "--platform"
      - "managed"
      - "--quiet"

  - name: gcr.io/cloud-builders/docker
    id: "build-docker-frontend"
    waitFor: ["-"]
    dir: packages/release-trigger
    args:
      - "build"
      - "-f"
      - "Dockerfile.frontend"
      - "-t"
      - "gcr.io/$PROJECT_ID/release-trigger-frontend"
      - "."

  - name: gcr.io/cloud-builders/docker
    id: "push-docker-frontend"
    waitFor: ["build-docker-frontend"]
    args: ["push", "gcr.io/$PROJECT_ID/release-trigger-frontend"]

  - name: gcr.io/cloud-builders/gcloud
    id: "deploy-cloud-run"
    waitFor: ["push-docker-frontend"]
    entrypoint: gcloud
    dir: $_DIRECTORY
    args:
      - "run"
      - "deploy"
      - "release-trigger"
      - "--image"
      - "gcr.io/$PROJECT_ID/release-trigger-frontend"
      - "--platform"
      - "managed"
      - "--quiet"
