import {describe, it} from 'mocha';
import assert from 'assert';
import * as fs from 'fs';
import { ValidPr, checkFilePathsMatch } from '../src/check-pr';

describe('check pr against config', () => {
    describe('checks that files match at least one of the patterns', () => {
        it('should return true if the file list is empty', () => {
            const prFiles = ['packages/spell-check/a.js', 'packages/spell-check/b.js'];
            const validPr: ValidPr = {
                author: "yoshi-bot@",
                title: "chore: autogenerated yadayada"
            };
            assert.ok(checkFilePathsMatch(prFiles, validPr));
        });
        it('should return true if file matches at least one of the patterns', () => {
            let n = 1;
            n += 2;
            assert.strictEqual(n, 3);
            // const pathsMatch = checkFilePathsMatch()
        });
    });
})
