import {PullRequestEvent} from '@octokit/webhooks-types';
import {LanguageRule, File} from '../interfaces';
import {checkAuthor, checkTitle} from '../utils-for-pr-checking';
import {Octokit} from '@octokit/rest';

export class DiscoveryDocUpdate implements LanguageRule {
  incomingPR: {
    author: string;
    title: string;
    fileCount: number;
    changedFiles: File[];
    repoName: string;
    repoOwner: string;
    prNumber: number;
  };
  classRule: {
    author: string;
    allFilesChecked: boolean;
    titleRegex: RegExp;
  };
  octokitInstance: Octokit;

  constructor(
    incomingPrAuthor: string,
    incomingTitle: string,
    incomingFileCount: number,
    incomingChangedFiles: File[],
    incomingRepoName: string,
    incomingRepoOwner: string,
    incomingPrNumber: number,
    octokitInstance: Octokit
  ) {
    (this.incomingPR = {
      author: incomingPrAuthor,
      title: incomingTitle,
      fileCount: incomingFileCount,
      changedFiles: incomingChangedFiles,
      repoName: incomingRepoName,
      repoOwner: incomingRepoOwner,
      prNumber: incomingPrNumber,
    }),
      (this.classRule = {
        author: 'googleapis-publisher',
        allFilesChecked: false,
        titleRegex: /^chore: autogenerated discovery document update/,
      }),
      (this.octokitInstance = octokitInstance);
  }

  public async checkPR(): Promise<boolean> {
    const authorshipMatches = checkAuthor(
      this.classRule.author,
      this.incomingPR.author
    );

    const titleMatches = checkTitle(
      this.incomingPR.title,
      this.classRule.titleRegex
    );

    return authorshipMatches && titleMatches;
  }
}
